#!/usr/bin/python

import sys
import os
import shutil
from optparse import OptionParser
import subprocess
import time
import os.path
import datetime

if os.path.isfile("files/welcome.jpg") == False:
    print("Expecting possible file to send in files/welcome.jpg")
    sys.exit()

CHECKINTERVAL = 2
start = datetime.time(12, 00)
end = datetime.time(23, 00)
now = datetime.datetime.now().time()
KNOWN_MACS = [line.rstrip('\n') for line in open('found_mac_addresses.txt')]

if __name__ == "__main__":
    while True:
        if start < now and now > end:
            print("Date surpassed curfew, wait quite a while")
            time.sleep(600)
            continue

        process = subprocess.Popen("/usr/bin/hcitool scan | grep -v Scanning | cut -f2", shell=True, stdout=subprocess.PIPE)
        process.wait()

	MACS = process.stdout.read()
        for MAC in MACS.splitlines():
            if MAC in KNOWN_MACS:
                continue

            if process.returncode == 0:
                print("MAC Found: " + MAC)
                with open("found_mac_addresses.txt", "a") as macaddresses:
                    #macaddresses.write(MAC + "\n")
			print("")
		
		process = subprocess.Popen('sdptool browse ' + MAC, shell=True, stdout=subprocess.PIPE)
		process.wait()
		INPUT = process.stdout.read()
		CHECKING = False
		CHANNEL = 0
		for LINE in INPUT.splitlines():
			if CHECKING == True:
				if "Channel" in LINE:
					CHANNEL = LINE[-2:]
					break

			if "0x1105" in LINE: 
				CHECKING = True
    				continue

		subprocess.Popen('obexftp -b ' + MAC + ' --channel ' + CHANNEL.strip() + ' -p files/welcome.jpg', shell=True, stdout=subprocess.PIPE)

		
        time.sleep(CHECKINTERVAL)
