#!/usr/bin/python

import sys
import os
import shutil
from optparse import OptionParser
import subprocess
import time

#DEVICEADDR = "64:77:91:B7:7A:58"  # bluetooth device address
CHECKINTERVAL = 2  # device pinged at this interval (seconds) when screen is unlocked

if __name__ == "__main__":
    while True:
        process = subprocess.Popen("/usr/bin/hcitool scan | grep -v Scanning | cut -f2", shell=True, stdout=subprocess.PIPE)
        process.wait()

	MACS = process.stdout.read()
        for MAC in MACS.splitlines():
 	    print(MAC)

            if process.returncode == 0:
                print("MAC Found: " + MAC)
#obexftp --uuid none --noconn --nopath –-bluetooth 64:77:91:B7:7A:58 --put LICENSE 
#bluetooth-sendto --device=64:77:91:B7:7A:58 LICENSE 
		#subprocess.Popen(['gnome-screensaver-command', '--deactivate'], shell=False, stdout=subprocess.PIPE)

        time.sleep(CHECKINTERVAL)
