#!/usr/bin/python

import sys
import os
import shutil
from optparse import OptionParser
import subprocess
import time
import os.path

if os.path.isfile("files/welcome.jpg") == False:
    print("Expecting possible file to send in files/welcome.jpg")
    sys.exit()

CHECKINTERVAL = 2  # device pinged at this interval (seconds) when screen is unlocked
start = datetime.time(8, 0)
end = datetime.time(19, 00)
now = datetime.datetime.now().time()

if start > now < end:
    print("invalid date")
    sys.exit()


KNOWN_MACS = [line.rstrip('\n') for line in open('found_mac_addresses.txt')]

if __name__ == "__main__":
    while True:
        #process = subprocess.Popen("/usr/bin/hcitool scan | grep -v Scanning | cut -f2", shell=True, stdout=subprocess.PIPE)
        #process.wait()

	    #MACS = process.stdout.read()
        MACS = "64:77:91:B7:7A:58"

        for MAC in MACS.splitlines():
            if MAC in KNOWN_MACS:
                continue

            #if process.returncode == 0:
            if 1:
                print("MAC Found: " + MAC)
                with open("found_mac_addresses.txt", "a") as macaddresses:
                    macaddresses.write(MAC + "\n")
                subprocess.Popen('bluetooth-sendto --device=' + MAC + ' files/welcome.jpg', shell=False, stdout=subprocess.PIPE)

        time.sleep(CHECKINTERVAL)