#!/usr/bin/python

import sys
import os
import shutil
from optparse import OptionParser
import subprocess
import time
import os.path
import datetime

if os.path.isfile("files/welcome.jpg") == False:
    print("Expecting possible file to send in files/welcome.jpg")
    sys.exit()

CHECKINTERVAL = 2
start = datetime.time(12, 00)
end = datetime.time(19, 00)
now = datetime.datetime.now().time()
KNOWN_MACS = [line.rstrip('\n') for line in open('found_mac_addresses.txt')]

if __name__ == "__main__":
    while True:
        if start > now or now > end:
            print("Date surpassed curfew, wait quite a while")
            time.sleep(600)
            continue

        process = subprocess.Popen("/usr/bin/hcitool scan | grep -v Scanning | cut -f2", shell=True, stdout=subprocess.PIPE)
        process.wait()

	MACS = process.stdout.read()
        for MAC in MACS.splitlines():
            if MAC in KNOWN_MACS:
                continue

            #if process.returncode == 0:
            if 1:
                print("MAC Found: " + MAC)
                with open("found_mac_addresses.txt", "a") as macaddresses:
                    macaddresses.write(MAC + "\n")
                subprocess.Popen('bluetooth-sendto --device=' + MAC + ' files/welcome.jpg', shell=False, stdout=subprocess.PIPE)

        time.sleep(CHECKINTERVAL)